### ISSUE TITLE
Driver flighting is not found in partner centner .

### ISSUE THREAD

**Issue by tzf-key** [MicrosoftDocs/windows-driver-docs.zh-cn#1]
I did not find a sending request to register Driver Filghting based on the description of the Driver Filghting document.
Does anyone know where the registration entrance is now?

**Comment by srvbpigh** [comment]
Hello, @tzf-key
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @tzf-key

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
