### ISSUE TITLE
标题与最后一节出现翻译错误

### ISSUE THREAD

**Issue by AnLazyOtter** [MicrosoftDocs/windows-driver-docs.zh-cn#10]
原文：Debugging Tools for Windows New for Windows 10 - Windows drivers
译文：对于 Windows 10 的新的 Windows 调试工具 - Windows drivers
建议：Windows 调试工具：Windows 10 的新增功能 - Windows drivers
说明：使网页标题与页面标题一致。

原文：For information on downloading the debugging tools, see Download Debugging Tools for Windows.
译文：下载调试工具的信息，请参阅&lt;a href="debugger-download-tools" data-linktype="relative-path"&gt;的 Windows 中下载调试的工具&lt;/a&gt;。
建议：：要下载调试工具的信息，请访问：&lt;a href="debugger-download-tools" data-linktype="relative-path"&gt;下载适用于 Windows 的调试工具&lt;/a&gt;。
说明：目标网页标题与此链接的说明文字不一致。“参阅”→“访问：”是可选的更改。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 57f74573-854a-83fe-2abc-e386fc282f42
* Version Independent ID: 468d3fb7-8500-678e-f1d8-d1267b64a5c2
* Content: [对于 Windows 10 的新的 Windows 调试工具 - Windows drivers](https://docs.microsoft.com/zh-cn/windows-hardware/drivers/debugger/debugging-tools-for-windows--new-for-windows-10?source=docs#feedback)
* Content Source: [windows-driver-docs-pr/debugger/debugging-tools-for-windows--new-for-windows-10.md](https://github.com/MicrosoftDocs/windows-driver-docs.zh-cn/blob/live/windows-driver-docs-pr/debugger/debugging-tools-for-windows--new-for-windows-10.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by srvbpigh** [comment]
Hello, @AnLazyOtter
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
你好，@AnLazyOtter， 

感谢你的发布内容。 

当前不接受有关机器翻译内容的翻译问题的发布内容。 

我们重视你对人工翻译内容（用于训练机器翻译引擎）的反馈和建议，你的参与将逐渐提高人工翻译和机器翻译的质量。 

人工翻译主题可以通过每个内容文件标题中的 ms.translationtype 元数据值“HT”与机器翻译主题（使用“MT”作为元数据值）区别开。 

非常感谢你的支持。 

Microsoft DOCS 全球体验团队

**Comment by AnLazyOtter** [comment]
> 你好，@AnLazyOtter，
> 感谢你的发布内容。
> 当前不接受有关机器翻译内容的翻译问题的发布内容。
> 我们重视你对人工翻译内容（用于训练机器翻译引擎）的反馈和建议，你的参与将逐渐提高人工翻译和机器翻译的质量。
> 人工翻译主题可以通过每个内容文件标题中的 ms.translationtype 元数据值“HT”与机器翻译主题（使用“MT”作为元数据值）区别开。
> 非常感谢你的支持。
> Microsoft DOCS 全球体验团队

@ticianaciminari 
那么，我是否可以通过在GitHub.com中点击“编辑”按钮参与到这篇文章的改进呢？
In that case, if I can edit this page in GitHub.com to improve the translation?
