### ISSUE TITLE
关于xp的调试

### ISSUE THREAD

**Issue by niedabao1** [MicrosoftDocs/windows-driver-docs.zh-cn#11]
windows xp 的符号表在服务器里被删除了吗?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 162fe2fe-9216-f4c5-9f91-3df8776bb99e
* Version Independent ID: 013dbf6b-0790-9c11-24f4-dbf24d64401e
* Content: [下载 Windows 调试工具 - WinDbg - Windows drivers](https://docs.microsoft.com/zh-cn/windows-hardware/drivers/debugger/debugger-download-tools#feedback)
* Content Source: [windows-driver-docs-pr/debugger/debugger-download-tools.md](https://github.com/MicrosoftDocs/windows-driver-docs.zh-cn/blob/live/windows-driver-docs-pr/debugger/debugger-download-tools.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by srvbpigh** [comment]
Hello, @niedabao1
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by niedabao1** [comment]
so ......where  I can download windows xp symbol package? i want to debug win_xp but the windbg tell me can't got symbol table .

**Comment by V-vafune** [comment]
你好，@niedabao1  

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。  

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。  

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  

Microsoft DOCS International Team
