### ISSUE TITLE
请问什么是classId、winUsbId？是由Classs+SubClass组成？

### ISSUE THREAD

**Issue by SuperDcer** [MicrosoftDocs/windows-driver-docs.zh-cn#12]
请问什么是classId、winUsbId？是由Classs+SubClass组成？若没有指定Device capabilities，会出现什么结果？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b843acc8-3fa9-5f3a-a89b-9c8149914020
* Version Independent ID: 1c3e8047-ad68-29a0-d3e7-9bf842c27885
* Content: [如何将 USB 设备功能添加到应用部件清单 - Windows drivers](https://docs.microsoft.com/zh-cn/windows-hardware/drivers/usbcon/updating-the-app-manifest-with-usb-device-capabilities#feedback)
* Content Source: [windows-driver-docs-pr/usbcon/updating-the-app-manifest-with-usb-device-capabilities.md](https://github.com/MicrosoftDocs/windows-driver-docs.zh-cn/blob/live/windows-driver-docs-pr/usbcon/updating-the-app-manifest-with-usb-device-capabilities.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by srvbpigh** [comment]
Hello, @SuperDcer
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
你好，@SuperDcer 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/windows-driver-docs/issues/2084。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
