### ISSUE TITLE
错误地翻译了英文前缀

### ISSUE THREAD

**Issue by kooWZ** [MicrosoftDocs/windows-driver-docs.zh-cn#15]
将Ex翻译成了例如 etc.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 36058e63-e506-f9c0-f4f5-f850c811d6e9
* Version Independent ID: 074a1423-d15c-7c20-51dd-d283f9d7f274
* Content: [Zw 前缀的含义是什么 - Windows drivers](https://docs.microsoft.com/zh-cn/windows-hardware/drivers/kernel/what-does-the-zw-prefix-mean-#feedback)
* Content Source: [windows-driver-docs-pr/kernel/what-does-the-zw-prefix-mean-.md](https://github.com/MicrosoftDocs/windows-driver-docs.zh-cn/blob/live/windows-driver-docs-pr/kernel/what-does-the-zw-prefix-mean-.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by srvbpigh** [comment]
Hello, @kooWZ
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@kooWZ

感谢你的发布内容。 

当前不接受有关机器翻译内容的翻译问题的发布内容。 

我们重视你对人工翻译内容（用于训练机器翻译引擎）的反馈和建议，你的参与将逐渐提高人工翻译和机器翻译的质量。 

人工翻译主题可以通过每个内容文件标题中的 ms.translationtype 元数据值“HT”与机器翻译主题（使用“MT”作为元数据值）区别开。 

非常感谢你的支持。 

Microsoft DOCS 全球体验团队
