### ISSUE TITLE
请修正  采购订单

### ISSUE THREAD

**Issue by lsz7575** [MicrosoftDocs/windows-driver-docs.zh-cn#3]
采购订单	 电源管理器	PoSetPowerState

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 36058e63-e506-f9c0-f4f5-f850c811d6e9
* Version Independent ID: 074a1423-d15c-7c20-51dd-d283f9d7f274
* Content: [Zw 前缀是什么意思 - Windows drivers](https://docs.microsoft.com/zh-cn/windows-hardware/drivers/kernel/what-does-the-zw-prefix-mean-)
* Content Source: [windows-driver-docs-pr/kernel/what-does-the-zw-prefix-mean-.md](https://github.com/MicrosoftDocs/windows-driver-docs.zh-cn/blob/live/windows-driver-docs-pr/kernel/what-does-the-zw-prefix-mean-.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by srvbpigh** [comment]
Hello, @lsz7575
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@lsz7575

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/windows-hardware/drivers/kernel/what-does-the-zw-prefix-mean-

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
