### ISSUE TITLE
完全错误的翻译

### ISSUE THREAD

**Issue by wuhanwuxi** [MicrosoftDocs/windows-driver-docs.zh-cn#5]
“IHVs must not add filter drivers to the GNSS/Location stack.“ 翻译成了 “Ihv 必须将筛选器驱动程序添加到 GNSS/位置堆栈。” 完全翻译反了。如果机器翻译之后没有审查，那有什么好翻译的，我用google把英文页面翻译一下都比这个好用。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 64fac4af-ecc2-46b8-178c-d3bb32f80e68
* Version Independent ID: 297eeee8-de8e-4edf-4f07-b154b00b4e95
* Content: [GNSS 驱动程序概述 - Windows drivers](https://docs.microsoft.com/zh-cn/windows-hardware/drivers/gnss/gnss-driver-overview#feedback)
* Content Source: [windows-driver-docs-pr/gnss/gnss-driver-overview.md](https://github.com/MicrosoftDocs/windows-driver-docs.zh-cn/blob/live/windows-driver-docs-pr/gnss/gnss-driver-overview.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by srvbpigh** [comment]
Hello, @wuhanwuxi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@wuhanwuxi

感谢你的反馈。有问题的页面是采用机器翻译的，因此不一定容易理解。我们最近在右侧添加了“阅读英文版”选项，无需更改语言设置即可切换到的英文版。 


深深的祝福， 
Microsoft DOCS International Team
