### ISSUE TITLE
usb host 和 device 测试问题？

### ISSUE THREAD

**Issue by a305566** [MicrosoftDocs/windows-driver-docs.zh-cn#6]
现在需要对window主板和usb外设接入进行评估测试，是否有完整的可以提供？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5cbad219-645b-4478-e284-8136cb65f210
* Version Independent ID: b8628dca-0242-92c3-5830-b0c965c89438
* Content: [通用串行总线 (USB) - Windows drivers](https://docs.microsoft.com/zh-cn/windows-hardware/drivers/usbcon/)
* Content Source: [windows-driver-docs-pr/usbcon/index.md](https://github.com/MicrosoftDocs/windows-driver-docs.zh-cn/blob/live/windows-driver-docs-pr/usbcon/index.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by srvbpigh** [comment]
Hello, @a305566
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@a305566
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
