### ISSUE TITLE
机器翻译语言混乱

### ISSUE THREAD

**Issue by yyl-2020** [MicrosoftDocs/windows-driver-docs.zh-cn#8]
机器翻译英文-&gt;中文，很难理解

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ae60e131-28fe-cbda-f41f-62771cbb8db1
* Version Independent ID: bb54c373-19d8-77fd-bc63-d02b69fe0075
* Content: [始终可抢占且始终可中断 - Windows drivers](https://docs.microsoft.com/zh-cn/windows-hardware/drivers/kernel/always-preemptible-and-always-interruptible#feedback)
* Content Source: [windows-driver-docs-pr/kernel/always-preemptible-and-always-interruptible.md](https://github.com/MicrosoftDocs/windows-driver-docs.zh-cn/blob/live/windows-driver-docs-pr/kernel/always-preemptible-and-always-interruptible.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by srvbpigh** [comment]
Hello, @yyl-2020
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by DavidPrio** [comment]
你好，@yyl-2020 

感谢你的反馈。有问题的页面是采用机器翻译的，因此不一定容易理解。我们最近在右侧添加了“阅读英文版”选项，无需更改语言设置即可切换到的英文版。 

深深的祝福， 
Microsoft DOCS International Team
